server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    password: "password"
    # THis ususally would be a different DB but to save resouce we use the same instance with customer
    url: jdbc:postgresql://localhost:5432/fraud
    username: "postgres"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: "true"
        show-sql: true
      zipkin:
        base-url: http://localhost:9411

#        IF it breaks, create new fraud db on server 5050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true